quant_master_init:
    provider_uri: "~/.quant_master/quant_master_data/cn_data"
    region: cn
    kernels: 1
    joblib_backend: threading
market: &market csi300
benchmark: &benchmark SH000300
port_analysis_config: &port_analysis_config
    strategy:
        class: TopkDropoutStrategy
        module_path: quant_master.contrib.strategy
        kwargs:
            signal: <PRED>
            topk: 20
            n_drop: 1
    backtest:
        start_time: 2024-01-01
        end_time: 2026-04-30
        account: 100000000
        benchmark: *benchmark
        exchange_kwargs:
            limit_threshold: 0.095
            deal_price: close
            open_cost: 0.0001
            close_cost: 0.0006
            min_cost: 0
task:
    model:
        class: PretrainedSignalModel
        module_path: quant_master.contrib.model.pretrained_signal
        kwargs:
            signal_path: "C:/Users/15728/Desktop/quant_master/reports/MetaEnsemble/meta_icir_pred_top20_source.pkl"
            score_column: score
    dataset:
        class: DatasetH
        module_path: quant_master.data.dataset
        kwargs:
            handler:
                class: Alpha158
                module_path: quant_master.contrib.data.handler
                kwargs:
                    start_time: 2012-01-01
                    end_time: 2026-04-30
                    fit_start_time: 2012-01-01
                    fit_end_time: 2020-12-31
                    instruments: *market
            segments:
                train: [2012-01-01, 2020-12-31]
                valid: [2021-01-01, 2023-12-31]
                test: [2024-01-01, 2026-04-30]
    record:
        - class: SignalRecord
          module_path: quant_master.workflow.record_temp
          kwargs:
            model: <MODEL>
            dataset: <DATASET>
        - class: SigAnaRecord
          module_path: quant_master.workflow.record_temp
          kwargs:
            ana_long_short: False
            ann_scaler: 252
        - class: PortAnaRecord
          module_path: quant_master.workflow.record_temp
          kwargs:
            config: *port_analysis_config

